# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://prashanth9962.github.io/
baseurl:
title: Sri Prashanth
author: Sri Prashanth
description: Personal blog and resume
avatar: profile.png
email: prashanth.engr@email.com
github: https://github.com/prashanth9962 # username
linkedin: https://www.linkedin.com/in/sri-prashanth-k-p-283aaa66
#twitter: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


email_full: mailto:prashanth.engr@gmail.com
website: sriprashanth.com
website_full: sriprashanth.com
tel_full: 9962756271
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address: 44 Perth Street
#postcode: EH3 5BL
city: Chennai
country: India

# needed for travis-ci build
exclude: [vendor]
