# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://prashanth9962.github.io/
baseurl: /
title: Sri Prashanth
author: Sri Prashanth
description: Personal blog and resume
avatar: profile.png
email: prashanth.engr@email.com
github: prashanth9962/sustain # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
